version: 0.0
os: linux
files:
 - source: .
   destination: /var/www/html
hooks:
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 500
     runas: root
  ApplicationStart:
   - location: scripts/start_server
     timeout: 500
     runas: root