version: 0.0
os: linux
files:
 - source: ./build/
   destination: /var/www/html
   overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
  - location: scripts/install_app_dependencies
    timeout: 300
    runas: root
 